queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=^test \([0-9]+\.x, ubuntu-latest\)$

pull_request_rules:
  - name: Merge approved and green PRs with `merge when green` label
    conditions:
      - "#approved-reviews-by>=1"
      - status-success~=^test \([0-9]+\.x, ubuntu-latest\)$
      - base=master
      - label=merge when green
    actions:
      queue:
        method: squash
        commit_message: title+body
        name: default
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success~=^test \([0-9]+\.x, ubuntu-latest\)$
      - base=master
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabo
      queue:
        method: squash
        commit_message: title+body
        name: default
